// @generated by protoc-gen-aelf-es v1.0.0 with parameter "target=ts"
// @generated from file contract/hello_world_contract.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty } from "@bufbuild/protobuf";
import { Character } from "./hello_world_contract_pb.js";
import { Address } from "../aelf/core_pb.js";

/**
 * @generated from service HelloWorld
 */
export abstract class HelloWorldClient {


    /**
     * Actions
     * Define methods name and input/output.
     *
     * @generated from rpc HelloWorld.Initialize
     */
    abstract async Initialize(request: Empty): Promise<Empty> {
    // this is a send method
    }

    /**
     * @generated from rpc HelloWorld.CreateCharacter
     */
    abstract async CreateCharacter(request: Empty): Promise<Character> {
    // this is a send method
    }

    /**
     * Views
     *
     * @generated from rpc HelloWorld.GetMyCharacter
     */
    abstract async GetMyCharacter(request: Address): Promise<Character> {
    // this is a view method
    }
}
