// @generated by protoc-gen-aelf-es v1.0.0 with parameter "target=ts"
// @generated from file reference/acs6.proto (package acs6, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BytesValue } from "@bufbuild/protobuf";

/**
 * @generated from service acs6.RandomNumberProvideacsrContract
 */
export abstract class RandomNumberProvideacsrContractClient {


    /**
     * @generated from rpc acs6.RandomNumberProvideacsrContract.GetRandomBytes
     */
    abstract async GetRandomBytes(request: BytesValue): Promise<BytesValue> {
    // this is a view method
    }
}
